name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Incident Number from commit message
        id: extract_incident
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          # Extract pattern like INC followed by numbers
          INCIDENT=$(echo "$COMMIT_MSG" | grep -oE 'INC[0-9]+')
          if [ -z "$INCIDENT" ]; then
            echo "No Incident Number found in commit please recheck!"
            exit 1
          fi
          echo "INCIDENT=$INCIDENT" >> $GITHUB_ENV

      - name: Notify ServiceNow with Deployment ID
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -u "${{ secrets.SNOW_USER }}:${{ secrets.SNOW_PASS }}" \
            -d "{\"deployment_id\": \"$INCIDENT\", \"status\": \"in_progress\"}" \
            "https://<YOUR_INSTANCE>.service-now.com/api/622834/github_ci_webhook/webhook"
