name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Incident Number from Commit
        id: extract_incident
        run: |
          # Get latest commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Extract Incident ID (pattern: INC followed by digits)
          INCIDENT_ID=$(echo "$COMMIT_MSG" | grep -oE 'INC[0-9]+')

          if [ -z "$INCIDENT_ID" ]; then
            echo "No incident ID found in commit message!"
            INCIDENT_ID="NO_INC_FOUND"
          fi

          echo "incident_id=$INCIDENT_ID" >> $GITHUB_OUTPUT

      - name: Trigger ServiceNow Webhook
        run: |
          DEPLOYMENT_ID=${{ steps.extract_incident.outputs.incident_id }}
          echo "Deployment ID: $DEPLOYMENT_ID"

          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{
              \"deployment_id\": \"$DEPLOYMENT_ID\",
              \"status\": \"failure\",
              \"repo\": \"${{ github.repository }}\",
              \"commit\": \"${{ github.sha }}\"
            }" \
            https://dev284803.service-now.com/api/622834/github_ci_webhook/webhook
