name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Deployment ID
        run: |
          echo "DEPLOYMENT_ID=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Print Deployment ID
        run: echo "Deployment ID is $DEPLOYMENT_ID"

      - name: Notify ServiceNow
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.SNOW_TOKEN }}" \
            -d "{\"deployment_id\": \"$DEPLOYMENT_ID\", \"incident_number\": \"INC0010002\"}" \
            https://your-servicenow-instance/api/endpoint
